pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker-compose build
  displayName: 'docker-compose build'
- script: docker-compose up -d
  displayName: 'docker-compose up'
- script: sleep 30
- script: docker-compose down