pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker-compose build
  displayName: 'Build Containers'
- script: docker-compose up -d
  displayName: 'Start Containers'
- script: sleep 60
  displayName: 'Wait for containers to do some work'
- script: docker-compose down
  displayName: 'Remove Containers'